apiVersion: v1
kind: Service
metadata:
  name: notificationsapi
  namespace: fiapcloudgames
spec:
  selector:
    app: notificationsapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
